In [2]:
import requests
import json
import pandas as pd
import numpy as np
from fredapi import Fred

MINIMUM WAGE

In [10]:
file = 'minimum_wage_data.csv'
min_wage_df = pd.read_csv(file)
cols = min_wage_df.columns.values
cols[0] = 'year'
min_wage_df.columns = cols
min_wage_df['year'] = pd.to_datetime(min_wage_df['year'])
min_wage_df.set_index('year', inplace=True)
min_wage_df.head()

,AK,AL,AR,AZ,CA,CO,CT,DC,DE,FED,...,SD,TN,TX,UT,VA,VT,WA,WI,WV,WY
year,,,,,,,,,,,,,,,,,,,,,
1968-01-01,2.1,1.6,NaN,NaN,1.65,1.25,1.40,1.6,1.25,1.6,...,NaN,1.6,NaN,1.15,NaN,1.4,1.6,1.25,1.0,1.2
1969-01-01,2.1,1.6,NaN,NaN,1.65,1.25,1.40,1.6,1.25,1.6,...,NaN,1.6,NaN,1.15,NaN,1.4,1.6,1.25,1.0,1.2
1970-01-01,2.1,1.6,1.1,NaN,1.65,1.25,1.60,1.6,1.25,1.6,...,1.0,1.6,NaN,1.15,NaN,1.6,1.6,1.30,1.0,1.3
1971-01-01,2.1,1.6,1.1,NaN,1.65,1.25,1.60,1.6,1.25,1.6,...,1.0,1.6,NaN,1.15,NaN,1.6,1.6,1.30,1.0,1.3
1972-01-01,2.1,1.6,1.2,NaN,1.65,1.25,1.85,1.6,1.60,1.6,...,1.0,1.6,1.4,1.35,NaN,1.6,1.6,1.45,1.2,1.5

In [44]:
has_null = min_wage_df.columns[min_wage_df.isna().any()].tolist()

for col in has_null:
    #print(col)
    min_wage_df[col].fillna(min_wage_df['FED'], inplace=True)
#min_wage_df.fillna(min_wage_df.FED)
#min_wage_df[has_null].fillna(min_wage_df['FED'], inplace=True)
#min_wage_df[has_null].fillna(min_wage_df['FED'], inplace=True)
min_wage_df.head()

,AK,AL,AR,AZ,CA,CO,CT,DC,DE,FED,...,SD,TN,TX,UT,VA,VT,WA,WI,WV,WY
year,,,,,,,,,,,,,,,,,,,,,
1968-01-01,2.1,1.6,1.6,1.6,1.65,1.25,1.40,1.6,1.25,1.6,...,1.6,1.6,1.6,1.15,1.6,1.4,1.6,1.25,1.0,1.2
1969-01-01,2.1,1.6,1.6,1.6,1.65,1.25,1.40,1.6,1.25,1.6,...,1.6,1.6,1.6,1.15,1.6,1.4,1.6,1.25,1.0,1.2
1970-01-01,2.1,1.6,1.1,1.6,1.65,1.25,1.60,1.6,1.25,1.6,...,1.0,1.6,1.6,1.15,1.6,1.6,1.6,1.30,1.0,1.3
1971-01-01,2.1,1.6,1.1,1.6,1.65,1.25,1.60,1.6,1.25,1.6,...,1.0,1.6,1.6,1.15,1.6,1.6,1.6,1.30,1.0,1.3
1972-01-01,2.1,1.6,1.2,1.6,1.65,1.25,1.85,1.6,1.60,1.6,...,1.0,1.6,1.4,1.35,1.6,1.6,1.6,1.45,1.2,1.5

HOUSING

In [6]:
file_name_yearly = 'yearly_housing_prices.csv'
housing_df = pd.read_csv(file_name_yearly)
new_columns = housing_df.columns.values
new_columns[0] = 'year'
#housing_df
housing_df.columns = new_columns

housing_df['year'] = pd.to_datetime(housing_df['year'], format="%Y")

housing_df.head()
housing_df.reset_index()
housing_df.set_index('year')

,AK,AL,AR,AZ,CA,CO,CT,DC,DE,FL,...,TN,TX,UT,VA,VT,WA,WI,WV,WY,United States not seasonally adjusted
year,,,,,,,,,,,,,,,,,,,,,
1975-01-01,37.471667,36.267500,38.076667,29.530833,16.757500,20.508333,25.575000,19.543333,28.058333,33.545000,...,32.998333,33.966667,25.640000,28.783333,29.030000,18.110833,29.508333,45.932500,33.854167,24.484167
1976-01-01,41.563333,38.497500,40.632500,30.220000,19.393333,21.961667,27.039167,21.885833,29.014167,34.064167,...,34.730000,36.309167,28.165000,29.864167,30.019167,20.300000,31.236667,48.198333,37.790000,26.331667
1977-01-01,44.965000,40.751667,44.240000,32.535833,24.271667,24.668333,28.923333,25.658333,30.213333,34.849167,...,37.480833,39.923333,31.703333,32.081667,32.181667,24.068333,35.499167,51.022500,43.540833,29.515000
1978-01-01,49.288333,44.843333,48.285833,37.719167,28.767500,29.357500,32.940833,30.524167,31.867500,38.740000,...,41.288333,45.825000,36.996667,35.511667,35.867500,29.654167,40.240000,56.606667,50.797500,33.698333
1979-01-01,55.193333,49.214167,53.958333,46.006667,33.729167,34.292500,37.524167,36.221667,34.164167,44.133333,...,44.381667,53.243333,42.036667,39.210000,38.771667,34.487500,43.181667,60.722500,59.769167,38.250000
1980-01-01,55.758333,51.750833,57.023333,52.133333,38.613333,38.123333,38.959167,40.130833,39.241667,50.070000,...,47.090000,59.926667,44.977500,43.453333,41.681667,37.948333,44.491667,64.296667,62.866667,42.029167
1981-01-01,64.613333,52.526667,59.683333,55.506667,42.108333,40.345000,41.689167,41.429167,40.117500,53.804167,...,49.745000,64.410000,46.995000,45.562500,41.949167,38.960000,43.667500,66.550833,66.151667,44.406667
1982-01-01,75.913333,53.295000,58.595000,56.498333,42.840833,43.282500,42.121667,40.219167,41.106667,58.487500,...,51.030000,69.564167,47.534167,45.389167,42.037500,38.216667,42.754167,55.978333,67.780833,45.403333
1983-01-01,83.536667,55.337500,64.036667,58.965833,43.399167,44.607500,44.660833,39.379167,44.796667,59.344167,...,52.866667,72.095833,49.950833,49.426667,44.433333,38.556667,45.993333,63.480833,65.305000,47.201667
1984-01-01,85.624167,58.350833,64.683333,60.808333,44.559167,45.095833,49.980833,42.536667,48.147500,60.895000,...,53.422500,74.984167,49.764167,52.320000,48.234167,39.925833,46.848333,63.864167,63.129167,49.390833
1985-01-01,82.330833,60.033333,66.526667,61.899167,46.569167,45.054167,58.022500,44.365833,52.260833,61.385000,...,57.115000,75.990833,49.905000,54.969167,51.745000,40.996667,47.426667,63.103333,62.118333,51.911667
1986-01-01,79.063333,63.154167,68.298333,64.378333,49.515000,45.835833,72.326667,47.848333,58.328333,63.143333,...,60.541667,75.360833,50.025000,58.431667,57.490000,41.856667,48.989167,64.018333,59.860000,55.377500
1987-01-01,67.310833,65.499167,69.253333,65.365833,54.045833,45.255000,90.804167,53.844167,65.893333,65.120000,...,64.010833,71.311667,49.342500,64.045000,66.495000,43.319167,50.693333,65.940833,54.757500,59.247500
1988-01-01,68.689167,66.865000,69.030000,65.553333,61.760833,44.103333,98.145000,62.996667,73.030000,67.927500,...,66.099167,67.705833,48.032500,70.796667,75.934167,45.145000,52.795833,67.225000,51.445833,63.034167
1989-01-01,60.992500,68.460833,69.681667,65.372500,74.288333,44.238333,96.909167,70.250833,79.930833,70.794167,...,67.534167,67.286667,48.683333,76.579167,82.162500,50.780000,55.625833,68.630833,53.691667,67.680833
1990-01-01,64.683333,70.062500,70.740000,64.971667,80.690000,45.146667,92.018333,73.010833,82.886667,72.286667,...,68.362500,67.640833,50.428333,78.273333,83.693333,62.252500,58.665833,70.886667,57.469167,70.595000
1991-01-01,71.809167,71.410000,71.596667,65.217500,79.023333,46.517500,86.290833,71.947500,83.134167,72.590833,...,68.642500,69.064167,52.911667,77.601667,81.852500,65.779167,61.146667,73.571667,61.331667,70.856667
1992-01-01,75.000833,73.821667,74.185000,66.627500,77.170833,50.364167,83.565000,72.587500,83.050000,73.406667,...,70.235833,71.258333,56.885000,78.225833,81.633333,69.244167,65.085833,76.708333,65.495000,71.973333
1993-01-01,77.194167,76.927500,77.657500,68.175000,72.431667,55.648333,79.455000,69.797500,82.343333,74.418333,...,72.836667,73.741667,64.325000,78.568333,82.144167,71.983333,70.226667,80.204167,70.166667,72.504167
1994-01-01,81.441667,80.505000,82.580000,72.514167,69.637500,62.020000,78.715833,68.461667,82.405833,76.377500,...,77.170833,76.096667,75.019167,80.051667,82.182500,75.510000,75.345000,84.227500,77.044167,74.082500
1995-01-01,84.528333,83.494167,86.309167,76.379167,67.915833,66.416667,78.295833,67.477500,82.595000,77.978333,...,81.299167,77.828333,82.162500,80.775833,82.627500,77.024167,78.991667,87.560000,82.743333,75.341667
1996-01-01,87.486667,86.800833,88.810833,79.945833,67.524167,70.119167,78.355833,69.311667,83.374167,79.795000,...,85.623333,80.054167,88.512500,81.773333,83.137500,79.102500,82.240000,90.628333,86.390000,77.144167
1997-01-01,90.487500,89.677500,90.821667,82.765833,69.268333,73.960833,79.375833,69.854167,84.565000,82.025833,...,89.195000,82.197500,92.205833,83.389167,83.660000,82.845000,85.094167,92.628333,88.385833,79.488333
1998-01-01,93.346667,92.353333,92.526667,87.075833,75.478333,78.774167,82.616667,74.067500,86.987500,85.034167,...,92.440833,86.315833,94.920000,85.565000,85.761667,88.345000,88.608333,94.555000,91.071667,83.699167
1999-01-01,95.893333,95.965000,95.781667,92.099167,83.257500,86.415833,89.055000,82.681667,91.460833,89.577500,...,96.588333,91.700833,97.202500,90.265000,90.740833,93.667500,93.369167,96.991667,93.986667,89.519167
2000-01-01,98.462500,99.211667,98.976667,98.080000,94.576667,96.351667,97.111667,94.702500,97.351667,96.414167,...,99.755000,97.849167,99.843333,96.903333,97.755833,98.907500,99.076667,100.175000,98.174167,97.035000
2001-01-01,103.944167,101.381667,102.177500,103.193333,106.389167,104.486667,105.474167,111.797500,104.660000,105.827500,...,101.784167,103.067500,100.936667,105.679167,105.605000,103.232500,103.682500,101.910833,103.338333,104.557500
2002-01-01,110.491667,104.245000,106.025833,109.398333,120.667500,108.998333,117.085000,131.261667,114.015833,118.048333,...,104.817500,106.844167,102.404167,116.565833,114.828333,108.400000,109.621667,105.354167,110.811667,113.421667
2003-01-01,118.441667,107.865833,111.055833,117.751667,140.140000,111.225000,129.185000,153.360833,126.898333,133.390000,...,108.510000,109.671667,104.081667,129.720000,125.090000,115.280000,116.495833,109.987500,118.818333,123.835833
2004-01-01,128.885000,113.171667,117.516667,133.679167,170.983333,115.193333,143.254167,186.061667,143.855833,157.645000,...,113.643333,112.952500,109.447500,150.318333,140.565833,127.478333,124.312500,117.293333,130.503333,138.392500
2005-01-01,143.007500,121.222500,125.236667,177.256667,203.565833,120.046667,157.705833,222.057500,163.475000,200.279167,...,121.293333,118.091667,120.900000,177.671667,157.443333,147.240833,131.141667,125.151667,144.652500,155.622500
2006-01-01,154.714167,131.263333,131.558333,202.606667,213.810833,123.469167,163.086667,230.516667,175.227500,221.619167,...,129.970833,125.020833,141.765833,189.398333,165.799167,168.463333,135.270000,131.877500,162.314167,164.858333
2007-01-01,158.570000,135.204167,134.295000,194.838333,200.349167,123.310000,161.384167,232.952500,176.917500,206.920000,...,134.380000,130.231667,157.285000,185.915000,167.657500,177.445000,135.325833,134.746667,175.439167,162.358333
2008-01-01,156.216667,132.425833,130.844167,158.487500,156.746667,118.018333,152.438333,224.178333,167.699167,163.171667,...,130.520833,129.888333,149.265000,169.421667,164.385833,166.726667,130.893333,134.097500,176.100833,145.420833
2009-01-01,154.619167,126.431667,127.074167,123.291667,135.873333,116.486667,142.215833,217.462500,157.250833,132.675833,...,124.881667,128.438333,133.370000,158.952500,159.860000,148.705833,124.699167,131.650000,168.848333,132.365833
2010-01-01,154.900833,120.745833,124.090000,112.832500,136.546667,114.743333,138.871667,222.935000,150.245000,124.690000,...,122.009167,128.105833,126.655000,157.407500,158.207500,140.446667,120.789167,130.715000,164.285000,129.301667
2011-01-01,155.772500,114.957500,122.140833,103.489167,128.339167,111.218333,133.305833,228.852500,141.604167,117.021667,...,119.138333,126.067500,119.478333,153.389167,157.562500,129.023333,114.738333,129.138333,162.490000,123.129167
2012-01-01,157.005000,115.556667,124.500833,117.011667,132.145833,116.504167,129.288333,242.231667,138.743333,123.321667,...,120.376667,130.659167,124.596667,155.432500,157.097500,130.124167,112.562500,131.081667,164.967500,125.330000
2013-01-01,162.852500,119.116667,128.009167,137.656667,158.030833,128.048333,130.695000,271.162500,143.617500,139.147500,...,126.657500,140.645833,138.163333,163.775833,159.236667,143.805833,116.581667,134.837500,171.153333,137.620000
2014-01-01,167.454167,122.620833,129.605833,147.192500,175.247500,138.627500,131.260000,288.266667,148.015000,151.272500,...,132.802500,152.060833,145.417500,169.217500,160.190000,154.292500,120.680000,139.529167,177.675833,146.565000
2015-01-01,172.335833,126.021667,132.778333,156.666667,187.977500,153.259167,131.668333,305.436667,151.055000,165.565833,...,139.260000,163.688333,154.256667,172.636667,163.213333,168.842500,124.583333,142.292500,183.761667,154.656667
2016-01-01,175.464167,130.425833,136.439167,167.967500,202.085833,168.873333,132.295000,322.371667,154.638333,182.455833,...,147.972500,175.290833,166.509167,178.229167,165.663333,188.206667,131.150000,143.876667,185.905833,164.395000
2017-01-01,177.891667,135.627500,141.921667,181.546667,217.900000,185.144167,135.940833,339.159167,158.687500,199.493333,...,159.358333,187.741667,181.625000,185.279167,172.798333,212.040000,138.602500,146.151667,190.095833,175.720000
2018-01-01,179.895833,143.233333,147.800833,196.405000,233.456667,200.574167,139.262500,361.050833,166.535833,214.645833,...,170.589167,198.554167,200.583333,192.753333,181.246667,233.490000,147.658333,150.347500,197.212500,187.128333